import { DateTime } from 'luxon'
import type { Transaction } from '../types/Transaction'

/**
 * Paycheck-funded-month attribution ("shift month-end paycheck to next month").
 *
 * A semi-monthly earner's last paycheck lands in the final days of a month but
 * funds the 1st–14th of the following month, so calendar-month cash flow looks
 * short all month and snaps right only on payday. When the preference is on,
 * paycheck-generated rows dated inside the month-end window are attributed to
 * the month they fund — analytics only; the table and balances keep real dates.
 *
 * Mirrored by `period_stats` in src-tauri/src/commands/transactions.rs, which
 * applies the same window server-side for the median comparisons.
 */

/**
 * Days at the end of a month that count as "month-end". Four covers a
 * last-business-day payday pushed back across a weekend in every month length.
 */
export const MONTH_END_WINDOW_DAYS = 4

/** True when the ISO date falls inside the month-end window. */
export function isMonthEndDate(iso: string): boolean {
  const dt = DateTime.fromISO(iso)
  return dt.isValid && dt.day > dt.daysInMonth! - MONTH_END_WINDOW_DAYS
}

/** True when this row was generated by a paycheck dated in the month-end window. */
export function isMonthEndPaycheckRow(t: Transaction): boolean {
  return t.paycheckId != null && isMonthEndDate(t.date)
}

/**
 * ISO date of the 1st of the month this row's cash flow funds, or null when
 * the row isn't a month-end paycheck row (it funds its own calendar month).
 */
export function fundedMonthISO(t: Transaction): string | null {
  if (!isMonthEndPaycheckRow(t)) return null
  return DateTime.fromISO(t.date).plus({ months: 1 }).startOf('month').toISODate()!
}

/**
 * Re-date month-end paycheck rows (the net deposit and its pre-tax
 * contribution rows alike — they must move together or a month's savings would
 * outrun its income) to the 1st of the month they fund. Returns the input
 * array untouched when the preference is off.
 */
export function attributeToFundedMonth(txns: Transaction[], enabled: boolean): Transaction[] {
  if (!enabled) return txns
  return txns.map((t) => {
    const funded = fundedMonthISO(t)
    return funded == null ? t : { ...t, date: funded }
  })
}
