import { describe, it, expect } from 'vitest'
import { attributeToFundedMonth, fundedMonthISO, isMonthEndDate, isMonthEndPaycheckRow } from './attribution'
import type { Transaction } from '../types/Transaction'

function tx(overrides: Partial<Transaction>): Transaction {
  return {
    id: 1, accountId: 1, transferAccountId: null, amount: 100, description: '', date: '2026-05-01',
    type: 'income', category: 'fixed', isContribution: false, isWithdrawal: false, importSource: 'paycheck',
    generatedBalanceId: null, generatedBalanceToId: null, paycheckId: 1, vendorCategory: null, simplefinId: null, suppressedAs: null, rawDescription: null, createdAt: '', updatedAt: '',
    ...overrides,
  }
}

describe('isMonthEndPaycheckRow', () => {
  it('matches a paycheck row in the last 4 days of a 31-day month', () => {
    expect(isMonthEndPaycheckRow(tx({ date: '2026-01-28' }))).toBe(true)
    expect(isMonthEndPaycheckRow(tx({ date: '2026-01-31' }))).toBe(true)
  })

  it('does not match the 15th (mid-month paycheck stays put)', () => {
    expect(isMonthEndPaycheckRow(tx({ date: '2026-01-15' }))).toBe(false)
    expect(isMonthEndPaycheckRow(tx({ date: '2026-01-27' }))).toBe(false)
  })

  it('respects month length — the 27th is month-end in February but not March', () => {
    expect(isMonthEndPaycheckRow(tx({ date: '2026-02-27' }))).toBe(true)
    expect(isMonthEndPaycheckRow(tx({ date: '2026-03-27' }))).toBe(false)
  })

  it('handles a leap-year February', () => {
    expect(isMonthEndPaycheckRow(tx({ date: '2028-02-25' }))).toBe(false)
    expect(isMonthEndPaycheckRow(tx({ date: '2028-02-26' }))).toBe(true)
  })

  it('never matches rows not generated by a paycheck', () => {
    expect(isMonthEndPaycheckRow(tx({ date: '2026-01-31', paycheckId: null }))).toBe(false)
  })
})

describe('isMonthEndDate', () => {
  it('matches only the last 4 days of the month', () => {
    expect(isMonthEndDate('2026-01-27')).toBe(false)
    expect(isMonthEndDate('2026-01-28')).toBe(true)
    expect(isMonthEndDate('2026-02-24')).toBe(false)
    expect(isMonthEndDate('2026-02-25')).toBe(true)
  })

  it('rejects invalid dates', () => {
    expect(isMonthEndDate('not-a-date')).toBe(false)
  })
})

describe('fundedMonthISO', () => {
  it('returns the 1st of the next month for month-end paycheck rows', () => {
    expect(fundedMonthISO(tx({ date: '2026-06-30' }))).toBe('2026-07-01')
    expect(fundedMonthISO(tx({ date: '2026-12-29' }))).toBe('2027-01-01')
  })

  it('returns null for mid-month paychecks and non-paycheck rows', () => {
    expect(fundedMonthISO(tx({ date: '2026-06-15' }))).toBeNull()
    expect(fundedMonthISO(tx({ date: '2026-06-30', paycheckId: null }))).toBeNull()
  })
})

describe('attributeToFundedMonth', () => {
  it('moves a month-end paycheck deposit to the 1st of the next month', () => {
    const [t] = attributeToFundedMonth([tx({ date: '2026-05-29' })], true)
    expect(t.date).toBe('2026-06-01')
  })

  it('rolls December into January of the next year', () => {
    const [t] = attributeToFundedMonth([tx({ date: '2026-12-31' })], true)
    expect(t.date).toBe('2027-01-01')
  })

  it('moves pre-tax contribution rows together with their paycheck', () => {
    const [t] = attributeToFundedMonth(
      [tx({ date: '2026-06-30', isContribution: true, amount: 1030 })],
      true,
    )
    expect(t.date).toBe('2026-07-01')
  })

  it('leaves mid-month paychecks and non-paycheck rows alone', () => {
    const txns = [tx({ date: '2026-06-15' }), tx({ date: '2026-06-30', paycheckId: null })]
    expect(attributeToFundedMonth(txns, true).map((t) => t.date)).toEqual(['2026-06-15', '2026-06-30'])
  })

  it('is a no-op when the preference is off', () => {
    const txns = [tx({ date: '2026-06-30' })]
    expect(attributeToFundedMonth(txns, false)).toBe(txns)
  })
})
