// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = { id: number, name: string, type: string, institution: string | null, isActive: boolean, includeInFireCalculations: boolean, createdAt: string, 
/**
 * SimpleFIN account id this account is linked to, when bank sync is set up.
 */
simplefinId: string | null, 
/**
 * Count transfers INTO this account as spending (loan-style accounts where
 * the payment is the expense's only footprint). Defaults on for mortgages.
 */
countPaymentsAsExpense: boolean, };
