// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Account = { id: bigint, name: string, type: string, institution: string | null, isActive: boolean, includeInFireCalculations: boolean, createdAt: string, };
