// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountBalance = { id: number, accountId: number, balance: number, recordedAt: string, linkedTransactionId: number | null, 
/**
 * "manual" for user-entered/txn-generated snapshots, "simplefin" for synced ones.
 */
source: string, };
