// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetAttachment = { id: number, assetEventId: number, objectKey: string, originalName: string, provider: string, byteSize: bigint | null, createdAt: string, };
