// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeletionPreview = { transactions: bigint, paychecks: bigint, balanceSnapshots: bigint, budgetMonths: bigint, };
