// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FireProfile = { currentAge: bigint, targetRetirementAge: bigint, annualExpensesTarget: number, leanFireAnnualExpenses: number | null, fatFireAnnualExpenses: number | null, annualIncome: number, expectedReturnRate: number, inflationRate: number, };
