// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FireProfile = { dateOfBirth: string | null, targetRetirementAge: number, annualExpensesTarget: number, leanFireAnnualExpenses: number | null, fatFireAnnualExpenses: number | null, annualIncome: number, expectedReturnRate: number, inflationRate: number, 
/**
 * Safe withdrawal rate; 0.04 = the 4% rule (FIRE number = expenses × 25).
 */
withdrawalRate: number, hsaCoverage: string, onboardingCompleted: boolean, };
