// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HsaExpense = { id: number, 
/**
 * HSA account the expense was (or will be) reimbursed from; optional.
 */
accountId: number | null, 
/**
 * Date of service.
 */
date: string, description: string, 
/**
 * 'medical' | 'dental' | 'vision' | 'pharmacy' | 'other'
 */
category: string, amount: number, 
/**
 * Who the expense was for (family plans).
 */
person: string | null, 
/**
 * Doctor, clinic, or pharmacy name.
 */
provider: string | null, notes: string | null, 
/**
 * Whether money has been taken from the HSA for this expense.
 */
reimbursed: boolean, reimbursedDate: string | null, createdAt: string, updatedAt: string, hasAttachment: boolean, };
