// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportMapping = { id: number, name: string, config: string, createdAt: string, };
