// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaycheckDeduction = { label: string, amount: number, preTax: boolean, contributionAccountType: string | null, accountId: number | null, };
