// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeriodStats = {
  /** Calendar period key — "YYYY-MM" for months, "YYYY" for years. */
  period: string
  income: number
  /** Total spending, excluding savings/contributions. */
  expense: number
  /** Total savings / investment contributions (withdrawals subtract). */
  savings: number
  /** Income minus spending (savings is not subtracted — the money is still yours). */
  net: number
  catFixed: number
  catDiscretionary: number
  catUncategorized: number
}
