// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-period (month or year) aggregated cash-flow stats, used for median
 * comparison on the Transactions page. Each row is one calendar period.
 */
export type PeriodStats = { 
/**
 * Calendar period key — "YYYY-MM" for months, "YYYY" for years.
 */
period: string, income: number, 
/**
 * Total spending, excluding savings/contributions.
 */
expense: number, 
/**
 * Total savings / investment contributions (withdrawals subtract).
 */
savings: number, 
/**
 * Income minus spending (savings is not subtracted — the money is still yours).
 */
net: number, catFixed: number, catDiscretionary: number, catIrregular: number, catUncategorized: number, };
