// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One candidate duplicate pair for the post-import review: a SimpleFIN-imported
 * transaction and a non-SimpleFIN one (manual/CSV/paycheck) on the same account
 * that look like the same real-world event.
 */
export type SimpleFinDuplicateCandidate = { accountId: number, accountName: string, amount: number, 
/**
 * "income" | "expense" (transfers are excluded from matching).
 */
txnType: string, simplefinTxnId: number, simplefinDate: string, simplefinDescription: string, otherTxnId: number, otherDate: string, otherDescription: string, otherImportSource: string, 
/**
 * Resolution bucket: "ordinary" (delete the non-SimpleFIN row, keep its
 * snapshot), "net_deposit" (paycheck-linked deposit — higher stakes,
 * user opts in), or "contribution" (paycheck-linked row on an investment
 * account — resolution is reversed: delete the SimpleFIN row, which can
 * never carry is_contribution/paycheck_id).
 */
bucket: string, };
