// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimpleFinSyncSummary = { accountsSynced: number, transactionsAdded: number, snapshotsAdded: number, 
/**
 * Cross-account income/expense pairs collapsed into canonical transfers.
 */
transfersDetected: number, 
/**
 * Whether the pending-transaction cache changed this sync (the set is
 * wiped and re-inserted every time; this compares the row counts).
 */
pendingChanged: boolean, bridgeErrors: Array<string>, };
