// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimpleFinRemoteAccount = { id: string, name: string, org: string | null, 
/**
 * Balance exactly as the bank reports it (liabilities usually negative).
 */
balance: number, 
/**
 * "YYYY-MM-DD" of the bank's balance-date.
 */
balanceDate: string, currency: string | null, 
/**
 * Local account this SimpleFIN account is linked to, if any. Recomputed
 * from the `account` table on every read (never trusted from the cache).
 */
linkedAccountId: number | null, };
