// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the `simplefin-syncing` event: `syncing: true` when a sync
 * starts, `syncing: false` plus the outcome when it finishes — lets the
 * frontend surface progress/result notifications even for background syncs.
 */
export type SimpleFinSyncingEvent = { syncing: boolean, error: string | null, transactionsAdded: number, snapshotsAdded: number, };
