// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimpleFinSyncSummary = { accountsSynced: number, transactionsAdded: number, snapshotsAdded: number, bridgeErrors: Array<string>, };
