// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimpleFinRemoteAccount } from "./SimpleFinRemoteAccount";

export type SimpleFinStatus = { connected: boolean, claimedAt: string | null, lastAttemptAt: string | null, lastSuccessAt: string | null, lastError: string | null, 
/**
 * Messages from the bridge's `errors` field — typically "Connection to
 * <bank> may need attention". These arrive even on successful syncs.
 */
bridgeErrors: Array<string>, 
/**
 * Remote accounts seen on the last fetch (cached; no extra API call).
 */
accounts: Array<SimpleFinRemoteAccount>, };
