// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimpleFinSyncSummary = { accountsSynced: number, transactionsAdded: number, snapshotsAdded: number, 
/**
 * Cross-account income/expense pairs collapsed into canonical transfers.
 */
transfersDetected: number, bridgeErrors: Array<string>, };
