// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transaction still pending at the bank, cached for awareness display only.
 * Never enters `txn` and never counts toward any total — pending rows mutate
 * or vanish (even their SimpleFIN id can change once posted), so the cache is
 * wiped and re-inserted on every sync.
 */
export type SimpleFinPendingTransaction = { id: number, accountId: number, amount: number, description: string, 
/**
 * "YYYY-MM-DD" (transacted date when the bank sends one, else posted).
 */
date: string, 
/**
 * "income" | "expense" (sign-derived, same as the posted import path).
 */
txnType: string, simplefinId: string, };
