// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageInfo = { provider: string, bucketName: string | null, r2AccountId: string | null, s3Region: string | null, localPath: string, hasCredentials: boolean, };
