// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuppressRule = { id: number, keyword: string, 
/**
 * 'investment_activity' | 'fee' | 'interest'
 */
kind: string, 
/**
 * Scope the rule to one account; None applies to all accounts.
 */
accountId: number | null, createdAt: string, };
