// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncStatus = { 
/**
 * "local" | "synced"
 */
mode: string, 
/**
 * "idle" | "syncing" | "error"
 */
status: string, 
/**
 * epoch milliseconds of last successful sync, or null
 */
lastSyncedAt: number | null, lastError: string | null, };
