// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Transaction = { id: number, accountId: number, transferAccountId: number | null, amount: number, description: string, date: string, type: string, category: string, isContribution: boolean, importSource: string, generatedBalanceId: number | null, generatedBalanceToId: number | null, createdAt: string, updatedAt: string, };
