// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Transaction = { id: number, accountId: number, transferAccountId: number | null, amount: number, description: string, date: string, type: string, category: string, isContribution: boolean, isWithdrawal: boolean, importSource: string, generatedBalanceId: number | null, generatedBalanceToId: number | null, paycheckId: number | null, 
/**
 * Category supplied by the bank/bridge (SimpleFIN), separate from `category`.
 */
vendorCategory: string | null, 
/**
 * SimpleFIN transaction id, set only on synced transactions (dedup key).
 */
simplefinId: string | null, 
/**
 * Rule-derived noise kind ('investment_activity' | 'fee' | 'interest').
 * When set, the transaction is excluded from cash-flow analytics and
 * hidden from the default transactions list; balance math still sees it.
 */
suppressedAs: string | null, createdAt: string, updatedAt: string, };
