// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transaction } from "./Transaction";

export type TransactionPage = { rows: Array<Transaction>, totalCount: number, totalIncome: number, totalExpense: number, net: number, 
/**
 * Rows matching the filter that carry suppressed_as, regardless of the
 * include_suppressed flag — drives the "show suppressed (N)" toggle.
 */
suppressedCount: number, };
